package fr.formation.inti.entity;
// Generated 28 janv. 2022 � 16:12:24 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TUsers generated by hbm2java
 */
@Entity
@Table(name = "t_users", catalog = "bdformation", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class User implements java.io.Serializable {

	private Integer idUser;
	private String login;
	private String password;
	private Integer connectionNumber;
	private String empId;
	private Set<Role> role = new HashSet<Role>(0);

	public User() {
	}

	public User(String login, String password) {
		this.login = login;
		this.password = password;
	}

	public User(String login, String password, Integer connectionNumber, String empId, Set<Role> role) {
		this.login = login;
		this.password = password;
		this.connectionNumber = connectionNumber;
		this.empId = empId;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_user", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "login", unique = true, nullable = false, length = 65)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 65)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "connectionNumber")
	public Integer getConnectionNumber() {
		return this.connectionNumber;
	}

	public void setConnectionNumber(Integer connectionNumber) {
		this.connectionNumber = connectionNumber;
	}

	@Column(name = "emp_id", length = 45)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_users_role", catalog = "bdformation", joinColumns = {
			@JoinColumn(name = "id_user", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRole() {
		return this.role;
	}

	public void setRole(Set<Role> role) {
		this.role = role;
	}

}
